#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
dunstctl set-paused true
convert $PICTURE -blur $BLUR $PICTURE
i3lock -ni $PICTURE
dunstctl set-paused false
rm $PICTURE
