require("core.plugin_config.onedarkpro")
require("core.plugin_config.lualine")
-- require("core.plugin_config.treesitter")
-- require("core.plugin_config.jupynium")
require("core.plugin_config.lsp_config")
-- require("core.plugin_config.rust-tools")
-- require("core.plugin_config.telescope")
-- require("core.plugin_config.completions")
